src/Entity/Organisme.php
<?php

namespace App\Entity;

use App\Repository\OrganismeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OrganismeRepository::class)]
class Organisme
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $nom;

    #[ORM\Column(type: 'string', length: 255)]
    private $adresse;

    #[ORM\Column(type: 'string', length: 255)]
    private $numero_tel;

    #[ORM\Column(type: 'string', length: 255)]
    private $email_contact;

    #[ORM\OneToMany(mappedBy: 'organisme', targetEntity: Formation::class)]
    private $organisme;

    public function __construct()
    {
        $this->organisme = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getNumeroTel(): ?string
    {
        return $this->numero_tel;
    }

    public function setNumeroTel(string $numero_tel): self
    {
        $this->numero_tel = $numero_tel;

        return $this;
    }

    public function getEmailContact(): ?string
    {
        return $this->email_contact;
    }

    public function setEmailContact(string $email_contact): self
    {
        $this->email_contact = $email_contact;

        return $this;
    }

    /**
     * @return Collection<int, Formation>
     */
    public function getOrganisme(): Collection
    {
        return $this->organisme;
    }

    public function addOrganisme(Formation $organisme): self
    {
        if (!$this->organisme->contains($organisme)) {
            $this->organisme[] = $organisme;
            $organisme->setOrganisme($this);
        }

        return $this;
    }

    public function removeOrganisme(Formation $organisme): self
    {
        if ($this->organisme->removeElement($organisme)) {
            // set the owning side to null (unless already changed)
            if ($organisme->getOrganisme() === $this) {
                $organisme->setOrganisme(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->getNom();
    }
}

src/Form/OrganismeType.php
<?php

namespace App\Form;

use App\Entity\Organisme;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class OrganismeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('adresse')
            ->add('numero_tel', TextType::class, array('attr' => ['maxlength' => 10]))
            ->add('email_contact')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Organisme::class,
        ]);
    }
}

src/Controller/OrganismeController.php
<?php

namespace App\Controller;

use App\Entity\Organisme;
use App\Form\OrganismeType;
use App\Repository\OrganismeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/organisme')]
class OrganismeController extends AbstractController
{
    #[Route('/', name: 'app_organisme_index', methods: ['GET'])]
    public function index(OrganismeRepository $organismeRepository): Response
    {
        return $this->render('organisme/index.html.twig', [
            'organismes' => $organismeRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_organisme_new', methods: ['GET', 'POST'])]
    public function new(Request $request, OrganismeRepository $organismeRepository): Response
    {
        $organisme = new Organisme();
        $form = $this->createForm(OrganismeType::class, $organisme);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $organismeRepository->add($organisme, true);

            return $this->redirectToRoute('app_organisme_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('organisme/new.html.twig', [
            'organisme' => $organisme,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_organisme_show', methods: ['GET'])]
    public function show(Organisme $organisme): Response
    {
        return $this->render('organisme/show.html.twig', [
            'organisme' => $organisme,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_organisme_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Organisme $organisme, OrganismeRepository $organismeRepository): Response
    {
        $form = $this->createForm(OrganismeType::class, $organisme);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $organismeRepository->add($organisme, true);

            return $this->redirectToRoute('app_organisme_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('organisme/edit.html.twig', [
            'organisme' => $organisme,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_organisme_delete', methods: ['POST'])]
    public function delete(Request $request, Organisme $organisme, OrganismeRepository $organismeRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$organisme->getId(), $request->request->get('_token'))) {
            $organismeRepository->remove($organisme, true);
        }

        return $this->redirectToRoute('app_organisme_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/organisme/_delete_form.html.twig
<form method="post" action="{{ path('app_organisme_delete', {'id': organisme.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ organisme.id) }}">
    <button class="btn button-black">Supprimer</button>
</form>

templates/organisme/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/organisme/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Organisme{% endblock %}

{% block body %}
    <h1>Modifier : Organisme</h1>

    {{ include('organisme/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_organisme_index') }}" class="button button-outline">retour à la liste</a>

    {{ include('organisme/_delete_form.html.twig') }}
{% endblock %}

templates/organisme/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Organisme index{% endblock %}

{% block body %}
    <h1>Organisme </h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Adresse</th>
                <th>Numero_tel</th>
                <th>Email_contact</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for organisme in organismes %}
            <tr>
                <td>{{ organisme.id }}</td>
                <td>{{ organisme.nom }}</td>
                <td>{{ organisme.adresse }}</td>
                <td>{{ organisme.numeroTel }}</td>
                <td>{{ organisme.emailContact }}</td>
                <td>
                    <a href="{{ path('app_organisme_show', {'id': organisme.id}) }}" class="button button-outline"><i class="fa-solid fa-eye"></i>voir</a>
                    <a href="{{ path('app_organisme_edit', {'id': organisme.id}) }}" class="button"><i class="fa-solid fa-pen-to-square"></i>modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_organisme_new') }}">Ajouter</a>
{% endblock %}

templates/organisme/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Organisme{% endblock %}

{% block body %}
    <h1>Créer : Organisme</h1>

    {{ include('organisme/_form.html.twig') }}

    <a href="{{ path('app_organisme_index') }}" class="button button-outline">retour à la liste</a>
{% endblock %}

templates/organisme/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Organisme{% endblock %}

{% block body %}
    <h1>Organisme</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ organisme.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ organisme.nom }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ organisme.adresse }}</td>
            </tr>
            <tr>
                <th>Numero_tel</th>
                <td>{{ organisme.numeroTel }}</td>
            </tr>
            <tr>
                <th>Email_contact</th>
                <td>{{ organisme.emailContact }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_organisme_index') }}" class="button button-outline">retour à la liste</a>

    <a href="{{ path('app_organisme_edit', {'id': organisme.id}) }}" class="button"><i class="fa-solid fa-pen-to-square"></i>modifier</a>

    {{ include('organisme/_delete_form.html.twig') }}
{% endblock %}